name: Code Quality

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev python3-dev

    - name: Cache pip and pre-commit
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.cache/pre-commit
        key: ${{ runner.os }}-pip-precommit-${{ hashFiles('requirements.txt', '.pre-commit-config.yaml') }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
        # Install project dependencies for pylint
        pip install -r requirements.txt

    - name: Install pre-commit hooks
      run: pre-commit install

    - name: Run pre-commit
      run: pre-commit run --all-files

    - name: Upload lint results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: lint-results
        path: |
          *.log
          .pre-commit-hooks.yaml
