name: Code Quality

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev python3-dev

    - name: Cache pip and pre-commit
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.cache/pre-commit
        key: ${{ runner.os }}-pip-precommit-${{ hashFiles('requirements.txt', '.pre-commit-config.yaml') }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
        pip install -r requirements.txt

    - name: Run pre-commit (check only) on PR
      if: github.event_name == 'pull_request'
      run: |
        # Sprawdzanie bez modyfikacji plików
        pre-commit run --all-files --verbose || {
          echo "❌ Code style issues found!"
          echo "💡 To fix: run 'pre-commit run --all-files' locally and commit changes"
          exit 1
        }

    - name: Run pre-commit (with auto-fix) on push
      if: github.event_name == 'push'
      run: |
        pre-commit run --all-files || echo "Files were modified by pre-commit"

    - name: Commit auto-fixes on push
      if: github.event_name == 'push'
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "style: auto-fix code style issues [skip ci]"
          git push
          echo "✅ Code style issues auto-fixed and committed"
        else
          echo "✅ No code style issues found"
        fi
